//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUONOW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Skill { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Location { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.Guid> VendorId { get; set; }
        public Nullable<bool> IsProduct { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsValidated { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ArtistId { get; set; }
        public Nullable<bool> IsNew { get; set; }
    }
}
